#!/bin/bash

if git-rev-parse --verify HEAD 2>/dev/null
then
        against=HEAD
else
        # Initial commit: diff against an empty tree object
        against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

git diff-index --check --cached $against -- || exit 1

git diff-index --cached HEAD | while read -r LINE; do
  rights=$(echo "${LINE}" | awk '{ print $2; }')
  hash=$(echo "${LINE}" | awk '{ print $4; }')
  filename=$(echo "${LINE}" | awk '{ print $6; }')

  # TODO: Hack to exclude symlinks
  if [ "${rights}" != "120000" ]; then
    # check commit to /lib
    case "$filename" in
      lib/* )
        tmp=${filename:4}
        dir=${tmp%%/*}
        if ls "lib/${dir}/.gitignore"; then
          echo "$filename : file cannot be commited to lib"
          exit 1
        fi
      ;;
    esac
    # check for empty string at the end of file
    if !(git cat-file blob $hash | tail -c1 | grep '^$'); then
      echo "$filename : no empty line at the end"
      exit 1
    fi
    # check Lua syntax
    case "$filename" in
      *\.lua | *\.rockspec )
        out=$(git show "${hash}" | luac -p - 2>&1)
        if [ "$?" != "0" ]; then
          echo "${out//stdin/${filename}}" >&2
          exit 1
        fi
      ;;
    esac
  fi
done
