-- tserialize-autogen.lua: autogenerated random tests for tserialize
-- This file is a part of lua-nucleo library
-- Copyright (c) lua-nucleo authors (see file `COPYRIGHT` for the license)

local make_suite = assert(loadfile('test/test-lib/init/strict.lua'))(...)

math.randomseed(12345)

local check_ok = import 'test/test-lib/tserialize-test-utils.lua' { 'check_ok' }
local gen_random_dataset = import 'test/test-lib/table.lua' { 'gen_random_dataset' }

local test = make_suite("tserialize-autogenerated")

for i = 1, 500 do
  test ("Random autogen test#"..i) (function()
    check_ok(gen_random_dataset())
  end)
end

assert(test:run())
