--------------------------------------------------------------------------------
-- test-list.lua: the list of all tests in the library
-- This file is generated by lua-nucleo library
-- Copyright (c) lua-nucleo authors(see file `COPYRIGHT` for the license)
--------------------------------------------------------------------------------

return
{
  {
    type = 'data/generate-test-list/cases';
    path = 'test/data/generate-test-list/cases/0000-othertest.lua';
  };
  {
    type = 'data/generate-test-list/cases';
    path = 'test/data/generate-test-list/cases/0000-test-file.lua';
  };
  {
    type = 'data/generate-test-list/cases';
    path = 'test/data/generate-test-list/cases/0000-test_file_name.lua';
  };
  {
    type = 'data/generate-test-list/cases';
    path = 'test/data/generate-test-list/cases/0000-test_file_other-sometest.lua';
  };
}
